In [19]:
import pyreadr
import pandas as pd
from joblib import load, dump

In [20]:
cat = ['Cho', 'George', 'Hagrid', 'Harry', 'Hermione', 'JellyB', 'Jube', 'Merry', 'MrsNorris', 'Neville', 'Nimbus', 'Scabbers']

dataset = pd.DataFrame(columns=['Timestamp', 'X_Mean', 'X_Min', 'X_Max', 'X_Sum', 'X_sd', 'X_Skew',
        'X_Kurt', 'Y_Mean', 'Y_Min', 'Y_Max', 'Y_Sum', 'Y_sd', 'Y_Skew',
        'Y_Kurt', 'Z_Mean', 'Z_Min', 'Z_Max', 'Z_Sum', 'Z_sd', 'Z_Skew',
        'Z_Kurt', 'VM_Mean', 'VM_Min', 'VM_Max', 'VM_Sum', 'VM_sd', 'VM_Skew',
        'VM_Kurt', 'ODBA15_Mean', 'ODBA30_Mean', 'ODBA45_Mean', 'ODBA60_Mean',
        'ODBA90_Mean', 'Cor_XY', 'Cor_XZ', 'Cor_YZ', 'Class'])

for name in cat:
    label = load(f"./cat_data/{name}_label").reset_index(drop=True)
    attri = load(f"./cat_data/{name}_attri")
    #Drop data
    label.drop(["Timestamp", "Pen", "Cat_id"], axis=1, inplace=True)
    attri.drop(["Cat_id", "Position"], axis=1, inplace=True)
    #process and connect
    label['Class'] = label.idxmax(axis=1)
    combined = pd.concat([attri, label['Class']], axis=1)
    dataset = pd.concat([dataset, combined], axis=0)
dataset.reset_index(drop=True, inplace=True)

C:\Users\xianweng\AppData\Local\Temp\ipykernel_5084\19617022.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dataset = pd.concat([dataset, combined], axis=0)

In [4]:
display(dataset)

,Timestamp,X_Mean,X_Min,X_Max,X_Sum,X_sd,X_Skew,X_Kurt,Y_Mean,Y_Min,...,VM_Kurt,ODBA15_Mean,ODBA30_Mean,ODBA45_Mean,ODBA60_Mean,ODBA90_Mean,Cor_XY,Cor_XZ,Cor_YZ,Class
0,2021-06-30 09:14:41,-0.279233,-0.910,0.344,-8.377,0.296662,-0.496104,2.991796,0.364567,-0.273,...,2.990033,0.592407,0.802264,0.933307,1.001583,1.099664,-0.864660,0.338424,-0.443238,Other_Start
1,2021-06-30 09:14:42,0.179567,-0.391,0.641,5.387,0.308351,-0.217862,1.910330,-0.416367,-1.910,...,1.892210,0.830707,1.474916,1.702981,1.746810,1.817719,0.382320,-0.319408,-0.950556,Other_Start
2,2021-06-30 09:14:43,-0.275833,-0.965,0.633,-8.275,0.417541,0.621538,2.577680,-0.162633,-1.031,...,3.088838,0.597076,0.849042,1.151128,1.293263,1.239673,-0.668675,0.084749,-0.599981,Other_Start
3,2021-06-30 09:14:44,-0.232167,-1.738,0.965,-6.965,0.686159,-0.091652,2.395802,-0.185267,-1.203,...,2.142305,0.494913,0.968376,1.463414,1.652899,1.560079,0.579230,-0.769338,-0.886042,Other_Start
4,2021-06-30 09:14:45,0.217933,-0.297,0.844,6.538,0.291364,0.479735,2.692920,-0.230767,-1.539,...,3.297924,0.664260,1.177634,1.596520,1.666363,1.528409,0.391264,-0.629328,-0.839797,Other_Start
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167922,2021-06-30 14:11:06,0.070567,0.063,0.078,2.117,0.003520,0.154864,2.911375,-0.949400,-0.957,...,2.422067,0.009762,0.011296,0.011690,0.012631,0.019560,0.390913,0.100491,-0.071119,Inactive_Sitting.Stationary
167923,2021-06-30 14:11:07,0.071167,0.059,0.074,2.135,0.003940,-1.536991,4.821726,-0.945067,-0.949,...,2.957309,0.007933,0.009172,0.011141,0.012820,0.016180,-0.151496,-0.013186,-0.144340,Other_Outofsight
167924,2021-06-30 14:11:08,0.067067,0.059,0.074,2.012,0.003493,-0.254070,3.431413,-0.945067,-0.949,...,4.210386,0.006980,0.007660,0.008353,0.008932,0.009750,0.053960,0.058327,-0.174078,Other_Outofsight
167925,2021-06-30 14:11:09,0.067467,0.051,0.082,2.024,0.006642,-0.539069,4.009483,-0.948300,-0.977,...,3.427669,0.021709,0.023663,0.025134,0.026130,0.026109,-0.402861,0.471890,-0.198935,Other_Outofsight
167926,2021-06-30 14:11:10,0.078667,0.066,0.090,2.360,0.005665,0.219496,3.204777,-0.951133,-0.988,...,4.335053,0.021062,0.034072,0.043110,0.046482,0.048362,0.380845,-0.054087,-0.249783,Other_Outofsight

In [22]:
dataset = dataset[~dataset['Class'].isin(['Other_Social.Allogrooming', 'Other_Start', 'Other_Outofsight', 'Other_Other', 'Other_ActigraphOff'])]
display(dataset["Class"].unique())

array(['Inactive_Standing.Stationary', 'Active_Walking',
       'Inactive_Sitting.Stationary', 'Inactive_Lying.Crouch',
       'Maintenance_Grooming', 'Maintenance_Scratching',
       'Inactive_Standing.Up', 'Inactive_Sitting.Down',
       'Inactive_Sitting.Up', 'Inactive_Lying.Down',
       'Maintenance_Nutrition.Eating', 'Maintenance_Littering.Digging',
       'Maintenance_Littering.None', 'Active_Trotting',
       'Maintenance_Littering.Urinating', 'Inactive_Lying.Resting',
       'Maintenance_Littering.Defecating'], dtype=object)

In [23]:
dataset.loc[dataset['Class'].isin(['Active_Playfight.Fighting', 'Active_Rubbing', 'Active_Playfight.Playing', 'Maintenance_Shake.Body', 'Active_Jumping.Vertical', 'Maintenance_Shake.Head', 'Active_Jumping.Horizontal', 'Active_Climbing']), 'Class'] = "active"
dataset.loc[dataset['Class'].isin(['Inactive_Standing.Stationary', 'Inactive_Standing.Up']), 'Class'] = "standing"
dataset.loc[dataset['Class'].isin(['Inactive_Sitting.Stationary', 'Inactive_Sitting.Down', 'Inactive_Sitting.Up']), 'Class'] = "sitting"
dataset.loc[dataset['Class'].isin(['Inactive_Lying.Crouch', 'Inactive_Lying.Down', 'Inactive_Lying.Resting']), 'Class'] = "lying"
dataset.loc[dataset['Class'].isin(['Active_Walking', 'Active_Trotting']), 'Class'] = "walk"
dataset.loc[dataset['Class'].isin(['Maintenance_Nutrition.Eating']), 'Class'] = "eat"
dataset.loc[dataset['Class'].isin(['Maintenance_Grooming']), 'Class'] = "groom"
dataset.loc[dataset['Class'].isin(['Maintenance_Scratching']), 'Class'] = "scratching"
dataset.loc[dataset['Class'].isin(['Maintenance_Littering.Digging', 'Maintenance_Littering.None', 'Maintenance_Littering.Urinating', 'Maintenance_Littering.Defecating']), 'Class'] = "other"
display(dataset["Class"].unique())
dataset.to_csv("./data/labeled_dataset1.csv", index=False)

array(['standing', 'walk', 'sitting', 'lying', 'groom', 'scratching',
       'eat', 'other'], dtype=object)